version: '3'
services:
  db:
    image: mysql/mysql-server
    container_name: absensi_db
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DBUSERNAME}"
      - "MYSQL_PASSWORD=${DBPASS}"
      - "MYSQL_DATABASE=${DBNAME}"   
  web:
    container_name: absensi_api
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"